### ISSUE TITLE
App crashes on (.vox) export

### ISSUE THREAD

**Issue by Indyandie** [aduermael/particubes-issue-tracker#21]
When I try exporting a magicavoxel file the app crashes.  Using an iPad Pro 2nd gen.

**Comment by aduermael** [comment]
It seems to happen on iPad only: https://twitter.com/ManeFunction/status/977158832320401411

I'll take a look at this, thanks for reporting the issue!

**Comment by aduermael** [comment]
I fixed it, it will work in the next version (1.1.4) 🙂

**Comment by Indyandie** [comment]
Woot thank you thank you!
