### ISSUE TITLE
It takes too much time when the app is going to background

### ISSUE THREAD

**Issue by aduermael** [aduermael/particubes-issue-tracker#5]
When closing Particubes (pressing home button), it's not perfectly smooth because of the world being saved. This shouldn't be done in main thread to improve the experience.

**Comment by aduermael** [comment]
Actually, maybe it's because we're waiting for the next frame to be rendered when saving, while this may never happen after `applicationWillResignActive` is called.

**Comment by gdevillele** [comment]
This should be fixed in the next update. 🐨
